#!/usr/bin/python

from formtools import *

startPage("Education/Workshop","workshop")
textInput("Title", "title")
textInput("Organization", "organization")
textInput("Website (not Facebook)", "website")
textInput("Social media address(es)", "facebook", placeholder="facebook / instagram / twitter")
textInput("Web link to best example of what you plan to do", "work_samples_website", "a good link will answer most of our questions, to program you effectively")
shorttextarea("Short description (140 chars)", "description_short", 2)
textarea("Long description (for website &amp; press releases)", "description_long", 6)
textInput("How many people will be teaching/running the workshop? (#)", "numberperformers")
textarea("Who are they and what are their roles?", "membersinfo", 6)
textInput("Are you based within 60 miles of Buffalo area? Will you need help with housing?", "out_of_town")
textarea("Are any of your group members in other proposals? Explain.", "proposaloverlap", 2)
yesnoInput("Is everyone in proposal over 21?", "over21")
yesnoInput("Would you like to be scheduled outdoors (sidewalks, porches, yards, parking lots, etc)?", "outdoorperformaces")
menuInput("Where do prefer to be scheduled?", "street_preferred", ["all indoor", "mostly indoor", "either indoor or outdoor", "mostly outdoor", "all outdoor"])
menuInput("Desired number of workshops", "numberperformances", [1,2,3,4,5])
textInput("Length of workshop: (in minutes)", "showlength")
textInput("Setup time (in minutes)", "setuptime")
textInput("Teardown time (in minutes)", "teardowntime")
textInput("Do you have a prearranged venue?", "prearrangedvenue")
textInput("Do you have an ideal venue in mind?", "idealvenue")
textInput("Is the workshop kid-friendly, or does it have age-sensitive content, or neither?", "agesensitive")
textInput("Proposal secondary categories, if any:", "secondary_category", placeholder="theatre, dance, visual art, literary, music, film/video")
print("</table></div>")

availabilitySection()

print("<div class='projectForm'>\n<h3>Workshop specifics</h3>\n<table class='alternategrey'>\n")
textarea("Outline of workshop schedule (list of activities and how long each will take)", "workshop_schedule")
textInput("What is the maximum number of participants you can have?", "maxparticipants")
textInput("Will you be charging an admission fee? How much? (Infringement requires that admission fees be no more than $20)", "admission")
textarea("What equipment will you be bringing? (include details on any unusual or unusually large setups)", "equipment_detail")
textInput("Do you require audio amplification or playback (Y/N)? If so, please give details.", "audio")
textInput("Do you require a projector/screen?", "projector")
textInput("Do you require chairs for the audience?", "chairs")
textInput("Will you need internet access?","internet")
print("</table></div>")

print("<div class='projectForm'>\n<h3>Final details</h3>\n<table class='alternategrey'>\n")
textarea("In what ways are you willing to volunteer?", "volunteer", 2, placeholder="equipment gopher, tech (audio/video/stage/etc), PR distribution, videography/photography, other")
textInput("Anything else we need to know?", "anythingelse")
textInput("Any questions?", "questions")
print("</table></div>")

endPage()

